# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'capybara'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'report_builder'
gem 'httparty', '0.21.0'
gem 'rspec'