# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'capybara'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'geckodriver-helper'
gem 'report_builder'
gem 'httparty'
gem 'rspec'
gem "site_prism"
gem 'cucumber_analytics'
gem 'rubocop'
